name: Pull Request

on:
  pull_request:
    types:
      - synchronize
      - labeled
      - unlabeled
      - opened
      - reopened

permissions:
  statuses: write

jobs:
  ready-deploy:
    runs-on: ubuntu-latest
    name: Label Check
    steps:
      - name: Set status check to success
        if: "contains(github.event.pull_request.labels.*.name, 'マージOK')"
        run: |
          curl --request POST \
            --url https://api.github.com/repos/${{github.repository}}/statuses/${{github.event.pull_request.head.sha}} \
            --header 'authorization: Bearer ${{secrets.GITHUB_TOKEN}}' \
            --header 'content-type: application/json' \
            --data '{
              "context": "Label Check",
              "state": "success",
              "description": "マージできます"
            }'
      - name: Set status check to pending
        if: "!contains(github.event.pull_request.labels.*.name, 'マージOK')"
        run: |
          curl --request POST \
            --url https://api.github.com/repos/${{github.repository}}/statuses/${{github.event.pull_request.head.sha}} \
            --header 'authorization: Bearer ${{secrets.GITHUB_TOKEN}}' \
            --header 'content-type: application/json' \
            --data '{
              "context": "Label Check",
              "state": "pending",
              "description": "\"マージOK\" ラベルを付けるとマージできます"
            }'
